### ISSUE TITLE
Why ResNet Naive Model show worse performance than VGG and Inception?

### ISSUE THREAD

**Issue by XiaotianM** [JifuZhao/Landmark_Recognition#1]
Hello.Thanks for your wonderful code. From your experiements, I find ResNet Naive Model show worse performance than VGG and Inception. Do you konw why?

**Comment by XiaotianM** [comment]
this is a gap of 30% accuracy between resnet naive model and vgg or inception naive model. I think its crazy

**Comment by JifuZhao** [comment]
This also looks weird to me. However, I am not sure the reason behind this. Compared with VGG and Inception nets, I guess one explanation would be the feature extracted from ResNet are not as good as the other nets for KNN model. The image used for this project is quite different from the ImageNet.

**Comment by XiaotianM** [comment]
Thanks for your reply.  I have printed the output of ResNet, I find the output is sparser than other networks. May be this is the reason why the feature extracted from ResNet are not as good as the other nets for KNN model.
